"""removed color added username

Revision ID: a5b700a5a56a
Revises: 79ebd118acb8
Create Date: 2022-08-03 17:37:40.302499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5b700a5a56a'
down_revision = '79ebd118acb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.String(length=200), nullable=False))
    op.create_unique_constraint(None, 'users', ['username'])
    op.drop_column('users', 'favorite_color')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('favorite_color', sa.VARCHAR(length=120), nullable=True))
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###
