"""changed name

Revision ID: c378b5dc8c6c
Revises: a5b700a5a56a
Create Date: 2022-08-07 18:46:19.246606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c378b5dc8c6c'
down_revision = 'a5b700a5a56a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blogs', 'slug')
    op.create_unique_constraint(None, 'users', ['username'])
    op.drop_column('users', 'favorite_color')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('favorite_color', sa.VARCHAR(length=120), nullable=True))
    op.drop_constraint(None, 'users', type_='unique')
    op.add_column('blogs', sa.Column('slug', sa.VARCHAR(length=200), nullable=True))
    # ### end Alembic commands ###
